server:
  port: ${zuul.port}

spring:
  application:
    name: "zuul-server"
  cloud:
    config:
      profile: dev
      label: dev

info:
  app:
    name: zuul-server
    address: localhost:8010
    env: dev
    version: 20180117A
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://zbw:123456@localhost:6001/eureka/

zuul:
  ignored-services: '*'
  retryable: false
  routes:
    api-demo:
      path: /demo/**
      service-id: "demo-service"
  add-host-header: true # 解决重定向问题
#    api-report:
#          path: /report/**
#          service-id: "winpos-report-service"
#          sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods

management:
  security:
    enabled: false   # 配置false,否则会有 401 错误
#  health:
#    redis:
#      enabled: true
#    mail:
#      enabled: false
#    db:
#      enabled: false
#    diskspace:
#      enabled: false

#endpoints:
#  shutdown:
#    enabled: true
#  restart:
#    enabled: true


# 1、路由问题： 默认规则，自定义映射规则，路径匹配，路由前缀
# 2、本地跳转，forward
# 3、cookie和头信息：设置routes下的sensitiveHeaders，使cookie和头信息能向下游传递
# 4、重定向：设置 addHostHeader : true