server:
  port: 8101

spring:
  application:
    name: "craw-zuul"

info:
  app:
    name: zuul-server
    address: localhost:8010
    env: dev
    version: 20180117A
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://zbw:123456@localhost:6001/eureka/

zuul:
  ignored-services: '*'
  retryable: false
  routes:
    api-demo:
      path: /demo/**
      service-id: "demo-service"
  add-host-header: true # 解决重定向问题
#      sensitive-headers:
#    api-shop:
#      path: /shop/**
#      service-id: "winpos-shop-service"
#      sensitive-headers:
#    api-system:
#      path: /base/**
#      service-id: "winpos-base-service"
#      sensitive-headers:
#    api-dishes:
#      path: /dishes/**
#      service-id: "winpos-dishes-service"
#      sensitive-headers:
#    api-config:
#      path: /config/**
#      service-id: "winpos-config-server"
#      sensitive-headers:
#    api-report:
#          path: /report/**
#          service-id: "winpos-report-service"
#          sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods

#management:
#  security:
#    enabled: false
#  health:
#    redis:
#      enabled: true
#    mail:
#      enabled: false
#    db:
#      enabled: false
#    diskspace:
#      enabled: false

#endpoints:
#  shutdown:
#    enabled: true
#  restart:
#    enabled: true


# 1、路由问题： 默认规则，自定义映射规则，路径匹配，路由前缀
# 2、本地跳转，forward
# 3、cookie和头信息：设置routes下的sensitiveHeaders，使cookie和头信息能向下游传递
# 4、重定向：设置 addHostHeader : true