spring:
  application:
    name: eureka-server
  profiles:
    active: dev

server:
  port: 8001

info:
  app:
    name: eureka-server
    address: localhost:8001
    env: dev
    version: 20180117A

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    register-with-eureka: false  #不向注册中心注册自己
    fetch-registry: false #不需要检索服务（erueka自己的）
