server:
  port: 8082
spring:
  application:
    name: demo-service
  profiles:
    active: dev
  cloud:
    loadbalancer:
      retry:
        enabled: true  # 开启重试机制

eureka:
  client:
    service-url:
      defaultZone: http://zbw:123456@localhost:6001/eureka/



