server:
  port: 8083

spring:
  application:
    name: "rabbit-demo"
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    url: ${jdbc.master}
    username: ${jdbc.username}
    password: ${jdbc.password}
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 47.98.123.156
    password: Zbw123456|
    port: 6379
    pool:
      max-active: 8
      min-idle: 0
      max-wait:  -1
      max-idle: 8

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      gated-launch: false

security:
#  basic:
#    enabled: true
#    path: /home/**,/backReason/**
  user:
    name: zbw
    password: 123456

management:
  security:
    enabled: false
  health:
    redis:
      enabled: false
    mail:
      enabled: false
    db:
      enabled: false
    diskspace:
      enabled: false

endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true

mybatis:
  mapperLocations: classpath:mapper/*.xml