server:
  port: 8083
spring:
  application:
    name: rabbitmq-hello-demo
  cloud:
    config:
      enabled: true
      profile: dev
      discovery:
        service-id: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://zbw:123456@localhost:6001/eureka/

# mac
# brew update
# brew install erlang
# brew install rabbitmq
# brew services start rabbitmq 启动
# localhost:15672 / guest guest