server:
  port: ${server.port}

spring:
  application:
    name: "rabbit-demo"
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    url: ${jdbc.master}
    username: ${jdbc.username}
    password: ${jdbc.password}
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: ${redis.database}
    host: ${redis.host}
    password: ${redis.password}
    port: ${redis.port}
    pool:
      max-active: ${redis.pool.max-active}
      min-idle: ${redis.pool.min-idle}
      max-wait:  ${redis.pool.max-wait}
      max-idle: ${redis.pool.max-idle}
#    sentinel:
#      master: ${redis.sentinel.master}
#      nodes: ${redis.sentinel.nodes}

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      gated-launch: false

security:
#  basic:
#    enabled: true
#    path: /home/**,/backReason/**
  user:
    name: zbw
    password: 123456

management:
  security:
    enabled: false
  health:
    redis:
      enabled: false
    mail:
      enabled: false
    db:
      enabled: false
    diskspace:
      enabled: false

endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true

mybatis:
  mapperLocations: classpath:mapper/*.xml