server:
  port: 8083

spring:
  application:
    name: "rabbit-demo"
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      gated-launch: false

security:
#  basic:
#    enabled: true
#    path: /home/**,/backReason/**
  user:
    name: zbw
    password: 123456

management:
  security:
    enabled: false
  health:
    redis:
      enabled: false
    mail:
      enabled: false
    db:
      enabled: false
    diskspace:
      enabled: false

endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://zbw:123456@localhost:6001/eureka/