spring:
  application:
    name: config-server
  profiles:
      active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhengbiwen999/demoConfig.git
          username: zhengbiwen999
          password: zbw910405

info:
  app:
    name: ${spring.application.name}
    address: ${spring.cloud.client.ipAddress}:${server.port}
    env: ${spring.profiles.active}
    version: 20180117A

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

security:
  basic:
    enabled: false

management:
  security:
    enabled: false
  health:
    redis:
      enabled: false