spring:
  application:
    name: config-server
  profiles:
      active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhengbiwen999/demoConfig.git
          username:
          password:

server:
  port: 6002
#info:
#  app:
#    name: ${spring.application.name}
#    address: ${spring.cloud.client.ipAddress}:${server.port}
#    env: ${spring.profiles.active}
#    version: 20180117A
#
eureka:
  client:
    service-url:
      defaultZone: http://zbw:123456@localhost:6001/eureka/

#
#security:
#  basic:
#    enabled: false
#
#management:
#  security:
#    enabled: false
#  health:
#    redis:
#      enabled: false