server:
  port: 8081
spring:
  application:
    name: ${test.server.applicationName}
  profiles:
    active: dev
  # 单数据源配置
  datasource:
    url: ${jdbc.master}
    username: ${jdbc.username}
    password: ${jdbc.password}
    driver-class-name: com.mysql.jdbc.Driver
#    testOnBorrow: ${jdbc.testOnBorrow}
#    initSize: ${jdbc.initSize}
#    minIdle: ${jdbc.minIdle}
#    maxActive: ${jdbc.maxActive}
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    metadata-map:
#      gated-launch: false
  client:
    service-url:
      defaultZone: ${eureka.defaultZone}

mybatis:
  mapperLocations: classpath:mapper/*.xml



